// Auto-generated
let project = new Project('call_hx');

project.addSources('Sources');
project.addLibrary("C:/Users/lubos/Downloads/Armory/armsdk//armory");
project.addLibrary("C:/Users/lubos/Downloads/Armory/armsdk//iron");
project.addParameter("--macro include('armory.trait')");
project.addParameter("--macro include('armory.trait.internal')");
project.addParameter('arm.EvalJS');
project.addParameter("--macro keep('arm.EvalJS')");
project.addParameter('arm.Plugin');
project.addParameter("--macro keep('arm.Plugin')");
project.addShaders('C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Shaders/blur_edge_pass.frag.glsl');
project.addShaders('C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Shaders/compositor_pass.frag.glsl');
project.addShaders('C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Shaders/compositor_pass.vert.glsl');
project.addShaders('C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Shaders/deferred_indirect.frag.glsl');
project.addShaders('C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Shaders/deferred_indirect.vert.glsl');
project.addShaders('C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Shaders/deferred_light.frag.glsl');
project.addShaders('C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Shaders/deferred_light_quad.frag.glsl');
project.addShaders('C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Shaders/pass.vert.glsl');
project.addShaders('C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Shaders/pass_lamp_volume.vert.glsl');
project.addShaders('C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Shaders/pass_viewray.vert.glsl');
project.addShaders('C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Shaders/smaa_blend_weight.frag.glsl');
project.addShaders('C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Shaders/smaa_blend_weight.vert.glsl');
project.addShaders('C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Shaders/smaa_edge_detect.frag.glsl');
project.addShaders('C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Shaders/smaa_edge_detect.vert.glsl');
project.addShaders('C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Shaders/smaa_neighborhood_blend.frag.glsl');
project.addShaders('C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Shaders/smaa_neighborhood_blend.vert.glsl');
project.addShaders('C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Shaders/ssao_pass.frag.glsl');
project.addShaders('C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Shaders/world_pass.frag.glsl');
project.addShaders('C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Shaders/world_pass.vert.glsl');
project.addShaders('build_call_hx/compiled/Shaders//Material_mesh.frag.glsl');
project.addShaders('build_call_hx/compiled/Shaders//Material_mesh.vert.glsl');
project.addShaders('build_call_hx/compiled/Shaders//Material_shadowmap.frag.glsl');
project.addShaders('build_call_hx/compiled/Shaders//Material_shadowmap.vert.glsl');
project.addAssets("build_call_hx/compiled/Shaders/Material_data.arm", { notinlist: true });
project.addAssets("build_call_hx/compiled/Shaders/shader_datas.arm", { notinlist: true });
project.addAssets("Bundled/my_plugin.js", { notinlist: true });
project.addAssets("C:/Users/lubos/Downloads/Armory/armsdk/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("C:/Users/lubos/Downloads/Armory/armsdk/armory/Assets/noise8.png", { notinlist: true });
project.addAssets("C:/Users/lubos/Downloads/Armory/armsdk/armory/Assets/smaa_area.png", { notinlist: true });
project.addAssets("C:/Users/lubos/Downloads/Armory/armsdk/armory/Assets/smaa_search.png", { notinlist: true });
project.addAssets("C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Assets/Scene.arm", { notinlist: true });
project.addAssets("C:/Users/lubos/Documents/Armory/armory_examples/call_hx/build_call_hx/compiled/Assets/meshes/mesh_Cube.arm", { notinlist: true });
project.addAssets("build_call_hx/compiled/Assets/envmaps/World_irradiance.arm", { notinlist: true });
project.addDefine('arm_deferred');
project.addDefine('arm_csm');
project.addDefine('rp_hdr');
project.addDefine('rp_renderer=Deferred');
project.addDefine('rp_depthprepass');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_size=1024');
project.addDefine('rp_background=World');
project.addDefine('rp_render_to_texture');
project.addDefine('rp_compositornodes');
project.addDefine('rp_antialiasing=SMAA');
project.addDefine('rp_supersampling=1');
project.addDefine('rp_gi=Off');
project.addDefine('rp_ssgi=SSAO');
project.addDefine('arm_shaderload');
project.addDefine('arm_soundcompress');
project.addDefine('arm_fast');


resolve(project);
